#!/bin/sh
set -euo pipefail
MODULES=$(jdeps --print-module-deps function.jar) && jlink --add-modules "$MODULES",jdk.crypto.ec  --compress 2 --no-header-files --no-man-pages --output /opt/dist
zip -r function.zip bootstrap function.jar opt/*
