#!/bin/sh
set -euo pipefail
/usr/lib/graalvm/bin/native-image --enable-url-protocols=https --allow-incomplete-classpath -H:+ReportExceptionStackTraces --no-server -jar $1 function
chmod 777 function
zip -j function.zip bootstrap function